apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-wide-app-resources
  namespace: argocd
spec:
  project: argocd-root
  source:
    repoURL: https://github.com/naoido/home-lab-kube-cluster-on-proxmox
    targetRevision: main
    path: k8s-manifests/apps/cluster-wide-app-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: 'cluster-wide-apps'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m