apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-tunnel-token
              key: token
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudflared
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: a897b42b-986d-4257-b401-b1505e04151d
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: argocd.object-t.com
      service: https://argocd-server.argocd.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
    - hostname: growi.object-t.com
      service: http://growi.growi.svc.cluster.local:3000
    - service: http_status:404