- name: Add ArgoCD Helm repo
  shell: |
    helm repo add argo https://argoproj.github.io/argo-helm
    helm repo update

- name: Copy base ArgoCD values.yaml from local repo
  copy:
    src: "{{ ansible_env.HOME }}/home-lab-kube-cluster-on-proxmox/k8s-manifests/argocd-helm-chart-values.yaml"
    dest: /tmp/argocd-helm-chart-values.yaml

- name: Append PAT to base values.yaml
  blockinfile:
    path: /tmp/argocd-helm-chart-values.yaml
    marker: "# {mark} ANSIBLE MANAGED BLOCK - REPO CREDENTIALS"
    block: |2
        repositories:
          home-lab-main:
            url: https://github.com/naoido/home-lab-kube-cluster-on-proxmox.git
            name: home-lab-main
            username: naoido
            password: {{ NEKO_BOT_SECRET_PAT }}
          home-lab-secrets:
            url: https://github.com/naoido/home-lab-kube-cluster-on-proxmox-secrets.git
            name: home-lab-secrets
            username: naoido
            password: {{ NEKO_BOT_SECRET_PAT }}
          neko-bot:
            url: https://github.com/naoido/neko-bot.git
            name: neko-bot
            username: naoido
            password: {{ NEKO_BOT_SECRET_PAT }}
          neko-bot-secret:
            url: https://github.com/naoido/neko-bot-secret.git
            name: neko-bot-secret
            username: naoido
            password: {{ NEKO_BOT_SECRET_PAT }}

- name: Wait for at least 1 Ready worker node
  shell: kubectl get nodes --no-headers | grep -v control-plane | grep -c ' Ready '
  register: worker_ready_count
  until: worker_ready_count.stdout|int > 0
  retries: 10
  delay: 10

- name: Install NFS CSI Driver
  shell: |
    helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --version 4.11.0

- name: Install ArgoCD core
  shell: >
    helm install argocd argo/argo-cd
    --version 7.8.13
    --create-namespace
    --namespace argocd
    --values /tmp/argocd-helm-chart-values.yaml
    --values {{ ansible_env.HOME }}/home-lab-kube-cluster-on-proxmox/k8s-manifests/secrets/argocd-oauth-config.yaml

- name: Install ArgoCD apps
  shell: >
    helm install argocd-apps argo/argocd-apps
    --version 2.0.2
    --namespace argocd
    --values https://raw.githubusercontent.com/naoido/home-lab-kube-cluster-on-proxmox/main/k8s-manifests/argocd-apps-helm-chart-values.yaml

- name: Remove temporary ArgoCD values file
  file:
    path: /tmp/argocd-helm-chart-values.yaml
    state: absent