- name: Add ArgoCD Helm repo
  shell: |
    helm repo add argo https://argoproj.github.io/argo-helm
    helm repo update

- name: Move private key to cloudinit user
  become: true
  shell: |
    mv /root/.ssh/neko-bot-secret-id_ed25519 /home/cloudinit/.ssh/neko-bot-secret-id_ed25519
    chown cloudinit:cloudinit /home/cloudinit/.ssh/neko-bot-secret-id_ed25519
    chmod 600 /home/cloudinit/.ssh/neko-bot-secret-id_ed25519

- name: Wait for at least 1 Ready worker node
  shell: kubectl get nodes --no-headers | grep -v control-plane | grep -c ' Ready '
  register: worker_ready_count
  until: worker_ready_count.stdout|int > 0
  retries: 10
  delay: 10

- name: Install ArgoCD core
  shell: >
    helm install argocd argo/argo-cd
    --version 7.8.13
    --create-namespace
    --namespace argocd
    --values https://raw.githubusercontent.com/naoido/home-lab-kube-cluster-on-proxmox/main/k8s-manifests/argocd-helm-chart-values.yaml

- name: Install ArgoCD apps
  shell: >
    helm install argocd-apps argo/argocd-apps
    --version 2.0.2
    --namespace argocd
    --values https://raw.githubusercontent.com/naoido/home-lab-kube-cluster-on-proxmox/main/k8s-manifests/argocd-apps-helm-chart-values.yaml