- name: Add ArgoCD Helm repo
  shell: |
    helm repo add argo https://argoproj.github.io/argo-helm
    helm repo update

- name: Download base ArgoCD values.yaml from GitHub
  get_url:
    url: https://raw.githubusercontent.com/naoido/home-lab-kube-cluster-on-proxmox/main/k8s-manifests/argocd-helm-chart-values.yaml
    dest: /tmp/argocd-helm-chart-values.yaml

- name: Append PAT to base values.yaml
  blockinfile:
    path: /tmp/argocd-helm-chart-values.yaml
    marker: "# {mark} ANSIBLE MANAGED BLOCK - REPO CREDENTIALS"
    block: |2
        repositories:
          neko-bot:
            url: https://github.com/naoido/neko-bot.git
            name: neko-bot
          neko-bot-secret:
            url: https://github.com/naoido/neko-bot-secret.git
            name: neko-bot-secret
            username: naoido
            password: {{ NEKO_BOT_SECRET_PAT }}

- name: Wait for at least 1 Ready worker node
  shell: kubectl get nodes --no-headers | grep -v control-plane | grep -c ' Ready '
  register: worker_ready_count
  until: worker_ready_count.stdout|int > 0
  retries: 10
  delay: 10

- name: Install ArgoCD core
  shell: >
    helm install argocd argo/argo-cd
    --version 7.8.13
    --create-namespace
    --namespace argocd
    --values /tmp/argocd-helm-chart-values.yaml

- name: Install ArgoCD apps
  shell: >
    helm install argocd-apps argo/argocd-apps
    --version 2.0.2
    --namespace argocd
    --values https://raw.githubusercontent.com/naoido/home-lab-kube-cluster-on-proxmox/main/k8s-manifests/argocd-apps-helm-chart-values.yaml

- name: Remove temporary ArgoCD values file
  file:
    path: /tmp/argocd-helm-chart-values.yaml
    state: absent