apiVersion: v1
kind: Service
metadata:
  name: growi
  namespace: growi
spec:
  selector:
    app: growi
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP