apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  description: The project of applications used by the entire cluster
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'cluster-wide-apps'
      server: https://kubernetes.default.svc
    - namespace: 'kube-system'
      server: https://kubernetes.default.svc
    - namespace: 'metallb-system'
      server: https://kubernetes.default.svc
    - namespace: 'sci-driver-nfs'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: neko-bot
  namespace: argocd
spec:
  description: neko-bot!
  sourceRepos:
    - '*'
  destinations:
    - namespace: neko-bot
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: object-t-minecraft
  namespace: argocd
spec:
  description: object-tMinecraftServer
  sourceRepos:
    - '*'
  destinations:
    - namespace: object-t-minecraft
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: growi
  namespace: argocd
spec:
  description: GROWI Team Wiki Application
  sourceRepos:
    - '*'
  destinations:
    - namespace: growi
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
