applications:
  argocd-root-app-of-apps:
    namespace: argocd
    project: argocd-root
    source:
      repoURL: https://github.com/naoido/home-lab-kube-cluster-on-proxmox
      targetRevision: main
      path: k8s-manifests/apps/root
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: true
      syncOptions:
        - CreateNamespace=true
      retry:
        limit: -1
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 2m
projects:
  argocd-root:
    namespace: argocd
    description: The top-level project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"